###
POST http://localhost:8080/auth/signup
content-type: application/json

{
    "name": "John Doe",
    "email": "john@example.com",
    "phone": "9999999999",
    "password": "xxxxxx"
}

###
POST http://localhost:8080/auth/login
content-type: application/json

{
    "name": "John Doe",
    "email": "john@example.com",
    "password": "xxxxxx"
}